packages:
  - "."
  - ".dependencies/altair"
  - ".dependencies/altair-plugin-adv"
  - ".dependencies/altair-plugin-flow"
  - ".dependencies/altair-plugin-vega-preview"
  - ".dependencies/altair/packages/preview-client"
  - ".dependencies/vega"
  - ".dependencies/vega/packages/protocol"
  - ".dependencies/vega-plugin-richtext"
  - ".dependencies/vega-ui-portable"

linkWorkspacePackages: true

allowBuilds:
  esbuild: true
